# Generated by Django 3.1.7 on 2021-06-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flight',
            new_name='AddFlight',
        ),
    ]
