# Generated by Django 3.1.7 on 2021-07-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_auto_20210630_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='country',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
