# Generated by Django 3.1.7 on 2021-07-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_airport_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=64)),
                ('lname', models.CharField(max_length=64)),
                ('flights', models.ManyToManyField(blank=True, related_name='passengers', to='flight.AddFlight')),
            ],
        ),
    ]
