# Generated by Django 3.1.7 on 2021-08-24 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saver', models.BigIntegerField()),
                ('economy', models.BigIntegerField()),
                ('business', models.BigIntegerField()),
                ('flight', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='flight.addflight')),
            ],
        ),
    ]
