# Generated by Django 3.1.7 on 2021-09-27 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=24)),
                ('address', models.CharField(max_length=100)),
                ('starting_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='price',
            name='business',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='price',
            name='economy',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='price',
            name='flight',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='addflight', to='flight.addflight'),
        ),
        migrations.AlterField(
            model_name='price',
            name='saver',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=24)),
                ('last_name', models.CharField(max_length=24)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=24)),
                ('no_of_adult_sit', models.PositiveSmallIntegerField()),
                ('no_of_child_sit', models.PositiveSmallIntegerField()),
                ('sit_type', models.CharField(max_length=16)),
                ('total_amount', models.PositiveIntegerField()),
                ('agent', models.ManyToManyField(blank=True, related_name='agent_booked', to='flight.Agent')),
                ('flight', models.ManyToManyField(blank=True, related_name='flight_boooked', to='flight.AddFlight')),
            ],
        ),
    ]
