# Generated by Django 3.1.7 on 2021-09-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0008_auto_20210927_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='return_flight',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
