# Generated by Django 3.1.7 on 2021-07-29 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight', '0004_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=32)),
                ('hotel', models.CharField(max_length=32)),
                ('duration', models.CharField(max_length=32)),
                ('price', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='FlightPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=128)),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_arrival', to='flight.airport')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_departure', to='flight.airport')),
            ],
        ),
    ]
